import 'package:flutter_config/flutter_config.dart';
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions android = FirebaseOptions(
    apiKey: FlutterConfig.get('FIREBASE_ANDROID_API_KEY'),
    appId: '1:710032068367:android:2dd391a89d8bfe1500387a',
    messagingSenderId: '710032068367',
    projectId: 'muict-itcs424-wechana',
    storageBucket: 'muict-itcs424-wechana.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: FlutterConfig.get('FIREBASE_IOS_API_KEY'),
    appId: '1:710032068367:ios:bb12fb017bda9d1800387a',
    messagingSenderId: '710032068367',
    projectId: 'muict-itcs424-wechana',
    storageBucket: 'muict-itcs424-wechana.appspot.com',
    iosClientId:
        '710032068367-2g5m69okmkhrthqb3tflg32m9g3414c5.apps.googleusercontent.com',
    iosBundleId: 'com.nakama.wechana',
  );
}
